spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
spring.main.allow-circular-references: true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=<Your email goes here>
spring.mail.password=<You need to create a password in the security settings of your gmail account>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

